### ISSUE TITLE
Cardinality constraints of FE DCAT AP

### ISSUE THREAD

**Issue by laurianvm** [fair-ease/IDDAS#2]
Hi everyone, 
There are initial cardinality constraints defined in the SHACL shapes (FE-DCAT-AP-SHACLshapes.ttl), 
but it would be really helpful if someone could double check these?
Thank you in advance!

**Comment by alko-k** [comment]
Hi @laurianvm I will have a look now

**Comment by laurianvm** [comment]
being handled in: https://github.com/fair-ease/asset-standards/issues/2
